global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"

    static_configs:

      - targets: ["localhost:9090"]

  - job_name: "traefik"
  # scrape_interval: 5s --> This overwrites the global interval

    static_configs:

      - targets: ["traefik.yourdomain.com:1138"] #traefik metrics port

  - job_name: "cadvisor"
    metrics_path: "/metrics"

    dns_sd_configs:
      - names:
          - "tasks.cadvisor" 
        type: "A"
        port: 8080

  - job_name: "node-exporter"
    metrics_path: "/metrics"

    dns_sd_configs:
     - names:
         - "tasks.node-exporter"
       type: "A"
       port: 9100
