version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'Password'
    volumes:
      - '/home/pihole/etc-pihole:/etc/pihole'
      - '/home/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'

    networks:
      - proxy
      
    cap_add:
      - NET_ADMIN
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.pihole.rule=Host(`yourdomain.com`)
        - traefik.http.routers.pihole.entrypoints=websecure
        - traefik.http.routers.pihole.tls.certresolver=myresolver
        - traefik.http.services.pihole.loadbalancer.server.port=80

networks:
  proxy:
    external: true  
