version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SERVER_DOMAIN: yourdomain.com
      GF_SERVER_ROOT_URL: https://yourdomain.com
      GF_PATHS_DATA: /.../grafana_data
    volumes:
      - /etc/hosts:/etc/hosts
      - /.../grafana_data:/.../grafana_data
    networks:
      - proxy
    deploy:
      replicas: 1 # It can only run on 1 node at a time because there is no centralized database.
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`grafana.yourdomain.com`)
        - traefik.http.routers.grafana.tls.certresolver=myresolver
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.middlewares=ipallowlist
        - traefik.http.services.grafana.loadbalancer.server.port=3000
networks:
  proxy:
    external: true
